/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(oqpskMod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b2dd2ca42d6042fc53b0414b187d9970)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/simple_oqpsk/oqpskMod.h>
// pydoc.h is automatically generated in the build directory
#include <oqpskMod_pydoc.h>

void bind_oqpskMod(py::module& m)
{

    using oqpskMod    = gr::simple_oqpsk::oqpskMod;


    py::class_<oqpskMod, gr::block, gr::basic_block,
        std::shared_ptr<oqpskMod>>(m, "oqpskMod", D(oqpskMod))

        .def(py::init(&oqpskMod::make),
           D(oqpskMod,make)
        )
        



        ;




}








