/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pduToConStream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d304707aed0c2c6badaf107175121db1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/simple_oqpsk/pduToConStream.h>
// pydoc.h is automatically generated in the build directory
#include <pduToConStream_pydoc.h>

void bind_pduToConStream(py::module& m)
{

    using pduToConStream    = gr::simple_oqpsk::pduToConStream;


    py::class_<pduToConStream, gr::block, gr::basic_block,
        std::shared_ptr<pduToConStream>>(m, "pduToConStream", D(pduToConStream))

        .def(py::init(&pduToConStream::make),
           D(pduToConStream,make)
        )
        



        ;




}








